name: Ironclad Test Harness

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demonstrate-vulnerability:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker container
      run: docker build -t ironclad-harness .

    - name: Run the test inside the container with KVM enabled
      # The --device /dev/kvm flag gives the container access to the host's
      # Kernel-based Virtual Machine, which is required for the emulator to run.
      run: docker run --device /dev/kvm ironclad-harness
